[package]
name = "memory_checker_client"
version = "0.1.0"
edition = "2021"

# 依赖项
[dependencies]
tokio = { version = "1", features = ["full"] }
sysinfo = "0.24.4"
hostname = "0.3"
local-ip-address = "0.6.3"

[lib]
crate-type = ["bin"] # 指定编译为可执行二进制文件